name: dtalk_robot
description: A starting point for Dart libraries or applications.
version: 1.1.1

environment:
  sdk: ^3.4.1

dependencies:
  crypto: ^3.0.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.16.0
